//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPLAN.EplAddIn.AutoTune {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class AutoTuneSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutoTuneSetting defaultInstance = ((AutoTuneSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutoTuneSetting())));
        
        public static AutoTuneSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string GenRules {
            get {
                return ((string)(this["GenRules"]));
            }
            set {
                this["GenRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string GenConfig {
            get {
                return ((string)(this["GenConfig"]));
            }
            set {
                this["GenConfig"] = value;
            }
        }
    }
}
